services:
  - type: web
    name: vvvk-portfolio
    env: node
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: free
    branch: main