services:
  - type: web
    name: vvvk-portfolio-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    branch: master
    autoDeploy: true

  - type: static
    name: vvvk-portfolio-client
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://vvvk-portfolio-server.onrender.com
    branch: master
    plan: free
    autoDeploy: true
